image: $CI_REGISTRY/jkridner/crystal
build:
  stage: build
  before_script:
    - sudo apk add shards
  script:
    - shards update
    - shards build
    - crystal build --prelude=../src/prelude.cr examples/test.cr -o bin/examples-test
    - crystal build --prelude=../src/prelude.cr examples/rabbit.cr -o bin/examples-rabbit
    - crystal build --prelude=../src/prelude.cr examples/rook.cr -o bin/examples-rook
    - crystal build --prelude=../src/prelude.cr examples/sniper.cr -o bin/examples-sniper
    - crystal build --prelude=../src/prelude.cr examples/target.cr -o bin/examples-target
  artifacts:
    paths:
      - bin/crystal-robots
      - bin/examples-test
      - bin/examples-rabbit
      - bin/examples-rook
      - bin/examples-sniper
      - bin/examples-target

test:
  stage: test
  before_script:
    - sudo apk add curl shards
    - scripts/install_wasmer.sh
    - . $HOME/.wasmer/wasmer.sh
    - shards update
  script:
    - crystal spec -v
    - crystal tool format --check
    - bin/crystal-robots -v
    - bin/crystal-robots
    - bin/examples-test
    - bin/examples-rabbit
    - bin/examples-rook
    - bin/examples-sniper
    - bin/examples-target
    - bin/crystal-robots -c examples/test -o examples/test.wasm
  artifacts:
    paths:
      - test.wasm

pages:
  stage: deploy
  script:
    - git config --global --add safe.directory /builds/jkridner/crystal-robots
    - crystal docs -o public --canonical-base-url=https://jkridner.beagleboard.io/crystal-robots --project-version `git show --format=%h -s` src/prelude.cr
  artifacts:
    paths:
      - public
