image: $CI_REGISTRY/jkridner/crystal
build:
  stage: build
  before_script:
    - sudo apk add shards
  script:
    - shards update
    - shards build
    - crystal build --prelude=../prelude.cr src/examples/rabbit.cr -o bin/examples-rabbit
  artifacts:
    paths:
      - bin/crystal-robots
      - bin/examples-rabbit

test:
  stage: test
  before_script:
    - sudo apk add curl shards
    - scripts/install_wasmer.sh
    - . $HOME/.wasmer/wasmer.sh
    - shards update
  script:
    - crystal spec -v
    - crystal tool format --check
    - bin/crystal-robots -v
    - bin/crystal-robots
    - bin/examples-rabbit

pages:
  stage: deploy
  script:
    - git config --global --add safe.directory /builds/jkridner/crystal-robots
    - crystal docs -o public --project-version `git show --format=%h -s` src/prelude.cr
  artifacts:
    paths:
      - public
