require "../spec_helper"

alias Docs = CrystalRobots::Web::Docs

# Docs::FILES is captured once, at this spec binary's own compile
# time, from whatever docs-api/ holds then -- normally nothing
# (docs-api/ is ignored and not generated by a plain `crystal spec`
# run), so most of these specs cover the "not built" fallback, the
# path a plain `crystal spec` run actually exercises. The richer,
# built-docs assertions only run when a prior `build-docs` step left
# docs-api/ populated before this binary was compiled, mirroring how
# scripts/ci.sh orders things (build-docs, then the final build).
describe Docs do
  it "reports not built when docs-api/ was empty at compile time" do
    Docs.built?.should be_false unless Docs.built?
  end

  it "refuses a path containing .. and a non-.html page lookup, regardless of build state" do
    Docs.page("../secret").should be_nil
    Docs.page("style.css").should be_nil
    Docs.asset("../../etc/passwd").should be_nil
  end

  if Docs.built?
    it "serves the index page wrapped for the Fossil chrome, with no script and no search box" do
      title, fragment = Docs.page("index.html").not_nil!
      title.should contain "crystal-robots"
      fragment.should contain "types-list"
      fragment.should_not contain "<script"
      fragment.should_not contain "<input"
    end

    it "keeps a doc comment's content and reports the right title for a nested type" do
      title, fragment = Docs.page("CrystalRobots/Compiler/Parser.html").not_nil!
      title.should eq "CrystalRobots::Compiler::Parser"
      fragment.should contain "One reduction pass"
    end

    it "does not serve stylesheets or scripts as assets; the page transform replaces them" do
      Docs.asset("css/style.css").should be_nil
      Docs.asset("js/doc.js").should be_nil
    end

    it "picks a MIME type for a non-HTML asset and falls back for an unknown extension" do
      Docs.mime("index.json").should eq "application/json"
      Docs.mime("nope.xyz").should eq "application/octet-stream"
    end
  else
    pending "serves built docs (run `crystal run src/cli.cr -- build-docs` before this spec binary compiles)"
  end
end
