(module
  (type $t0 (func))
  (type $t1 (func (result i32)))
  (type $t2 (func (param i32) (result i32)))
  (type $t3 (func (param i32 i32) (result i32)))
  (import "env" "puts" (func $env.puts (type $t2)))
  (func $run (export "run") (type $t1)
    (i32.const 42)
    (call $env.puts)
  )
)
